services:

  db:
    image: postgres:16
    container_name: zlagoda_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: zlagoda
      POSTGRES_USER: zlagoda_admin
      POSTGRES_PASSWORD: bdPassword2026
    ports:
      - "5432:5432"
    volumes:
      - zlagoda_data:/var/lib/postgresql/data
      # SQL files in ./db run automatically on first init
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: zlagoda_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: veronikagovorischeva@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dbpassword2026
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  zlagoda_data:
